# Generated by Django 5.2.6 on 2025-09-30 11:13

import canvases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_alter_canvas_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='join_code',
            field=models.CharField(default=canvases.models.generate_join_code, max_length=12, unique=True),
        ),
    ]
